#####################################################################
# Copyright (c) 2008 Open Kernel Labs, Inc. (Copyright Holder).
# All rights reserved.
# 
# 1. Redistribution and use of OKL4 (Software) in source and binary
# forms, with or without modification, are permitted provided that the
# following conditions are met:
# 
#     (a) Redistributions of source code must retain this clause 1
#         (including paragraphs (a), (b) and (c)), clause 2 and clause 3
#         (Licence Terms) and the above copyright notice.
# 
#     (b) Redistributions in binary form must reproduce the above
#         copyright notice and the Licence Terms in the documentation and/or
#         other materials provided with the distribution.
# 
#     (c) Redistributions in any form must be accompanied by information on
#         how to obtain complete source code for:
#        (i) the Software; and
#        (ii) all accompanying software that uses (or is intended to
#        use) the Software whether directly or indirectly.  Such source
#        code must:
#        (iii) either be included in the distribution or be available
#        for no more than the cost of distribution plus a nominal fee;
#        and
#        (iv) be licensed by each relevant holder of copyright under
#        either the Licence Terms (with an appropriate copyright notice)
#        or the terms of a licence which is approved by the Open Source
#        Initative.  For an executable file, "complete source code"
#        means the source code for all modules it contains and includes
#        associated build and other files reasonably required to produce
#        the executable.
# 
# 2. THIS SOFTWARE IS PROVIDED ``AS IS'' AND, TO THE EXTENT PERMITTED BY
# LAW, ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
# PURPOSE, OR NON-INFRINGEMENT, ARE DISCLAIMED.  WHERE ANY WARRANTY IS
# IMPLIED AND IS PREVENTED BY LAW FROM BEING DISCLAIMED THEN TO THE
# EXTENT PERMISSIBLE BY LAW: (A) THE WARRANTY IS READ DOWN IN FAVOUR OF
# THE COPYRIGHT HOLDER (AND, IN THE CASE OF A PARTICIPANT, THAT
# PARTICIPANT) AND (B) ANY LIMITATIONS PERMITTED BY LAW (INCLUDING AS TO
# THE EXTENT OF THE WARRANTY AND THE REMEDIES AVAILABLE IN THE EVENT OF
# BREACH) ARE DEEMED PART OF THIS LICENCE IN A FORM MOST FAVOURABLE TO
# THE COPYRIGHT HOLDER (AND, IN THE CASE OF A PARTICIPANT, THAT
# PARTICIPANT). IN THE LICENCE TERMS, "PARTICIPANT" INCLUDES EVERY
# PERSON WHO HAS CONTRIBUTED TO THE SOFTWARE OR WHO HAS BEEN INVOLVED IN
# THE DISTRIBUTION OR DISSEMINATION OF THE SOFTWARE.
# 
# 3. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR ANY OTHER PARTICIPANT BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#####################################################################

from nano_kernel_cell import KernelCell

Import('*')

#############################################################################
## Build L4
#############################################################################
if args.has_key("sdk"):
    sdk = args["sdk"]
else:
    sdk = False

if sdk:
    kernel_env = build.KengeCell(KernelCell, **args)
    kernel_env.args["kernel_type"] = args["config"]
else:
    kernel_env = build.KengeCell(KernelCell, name="nanokernel", **args)

kernel_env.process_global_config()
kernel_env.set_kernel_config(heap_align=16*1024)

if kernel_env.machine.device_core is not None:
    for (driver, server, memory, interrupt) in kernel_env.machine.v2_drivers:
        if sdk:
            # Only provide a serial device if not in production mode.
            if server == "vserial" and kernel_env.args['kernel_type'] != 'production':
                    kernel_env.add_use_device(["serial_dev"])
        else:
            # Provide a serial device unless ENABLE_DEBUG=False
            if server == "vserial" and get_bool_arg(kernel_env.args, "ENABLE_DEBUG", True):
                kernel_env.add_use_device(["serial_dev"])
        if server == "kinterrupt":
            kernel_env.add_use_device(["interrupt_dev"])

#kernel_env.Package("libs/compat")
#libs = kernel_env.Package("libs/atomic_ops")
#kernel_env.Package("libs/l4")
#kernel_env.Package("libs/soc")
#kernel_env.Package("libs/kernel")
#if kernel_env.toolchain.type == "gnu":
#    kernel_env.Package("libs/gcc")

if sdk:
    kernel = kernel_env.Package("nanokernel", sdk = sdk)
    Return("kernel")
else:
    kernel_env.Package("nanokernel")
    Return("kernel_env")
